# Generated by Django 3.0 on 2024-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role_Type',
            field=models.CharField(choices=[('0', '--- Select Your Role Type ---'), ('1', 'Team Lead'), ('2', 'Agent')], default='0', max_length=5),
        ),
    ]
