# Generated by Django 3.0 on 2024-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalsapp', '0006_workdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WorkDetail',
        ),
    ]
