# Generated by Django 3.0 on 2024-07-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalsapp', '0007_auto_20240721_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrequest',
            unique_together={('project', 'agent')},
        ),
    ]
